name: Build, Push bootc ISO, and Deploy VM on ESXi

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: 컨테이너 이미지 빌드
        run: podman build --network=host -t my_dashboard:latest .

      - name: ISO 파일명에 날짜 및 시간 적용 및 bootc로 ISO 변환
        run: |
          export ISO_DATE=$(date +"%Y%m%d%H%M")
          mkdir -p output
          sudo podman run --rm --privileged \
            --network=host \
            -v ./output:/output \
            -v /var/lib/containers/storage:/var/lib/containers/storage \
            quay.io/centos-bootc/bootc-image-builder:latest \
            --type iso \
            --output /output/my_dashboard-${ISO_DATE}.iso \
            localhost/my_dashboard:latest

      - name: Harbor 레지스트리 로그인
        run: podman login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }} harbor.bootc.com:80

      - name: ISO 파일 push (skopeo 사용)
        run: |
          export ISO_DATE=$(date +"%Y%m%d%H%M")
          sudo dnf install -y skopeo
          skopeo copy --dest-creds=${{ secrets.REGISTRY_USER }}:${{ secrets.REGISTRY_PASS }} \
            oci-archive:./output/my_dashboard-${ISO_DATE}.iso \
            docker://harbor.bootc.com:80/bootc/my_dashboard:${ISO_DATE}
