name: Build, Push bootc ISO, and Deploy VM on ESXi

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  ISO_FILENAME: my_dashboard_v1.iso

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: 컨테이너 이미지 빌드
        run: podman build --network=host -t localhost/my_dashboard:latest .

      - name: ISO 파일 빌드 및 output 디렉토리 생성
        run: |
          mkdir -p output
          sudo podman run --rm --privileged \
            --network=host \
            -v ./output:/output \
            -v /var/lib/containers/storage:/var/lib/containers/storage \
            quay.io/centos-bootc/bootc-image-builder:latest \
            --type iso \
            --output /output/${ISO_FILENAME} \
            localhost/my_dashboard:latest

      - name: Harbor 레지스트리 로그인
        run: podman login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }} harbor.bootc.com:80

      - name: ISO 파일 push (skopeo 사용)
        run: |
          sudo dnf install -y skopeo
          skopeo copy --dest-creds=${{ secrets.REGISTRY_USER }}:${{ secrets.REGISTRY_PASS }} \
            oci-archive:./output/${ISO_FILENAME} \
            docker://harbor.bootc.com:80/bootc/my_dashboard:${ISO_FILENAME}
