name: Update Bootc Client

on:
  workflow_dispatch:

env:
  IMAGE_NAME: my_dashboard
  HARBOR_REGISTRY: harbor.bootc.com:80  # 포트 명시적 추가

jobs:
  update:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      # 1. Podman insecure registry 설정
      - name: Configure Podman
        run: |
          sudo mkdir -p /etc/containers
          if ! grep -q "registries = \['$HARBOR_REGISTRY'\]" /etc/containers/registries.conf; then
            echo -e "[registries.insecure]\nregistries = ['$HARBOR_REGISTRY']" | sudo tee -a /etc/containers/registries.conf
          fi

      # 2. 버전 생성
      - name: Set Version
        id: version
        run: |
          if [ -n "${{ github.sha }}" ]; then
            echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          else
            echo "VERSION=manual-${{ github.run_id }}" >> $GITHUB_ENV
          fi

      # 3. 이미지 빌드 (포트 포함 태깅)
      - name: Build Image
        run: |
          podman build -f Containerfile_Update \
            -t $HARBOR_REGISTRY/smarthome/$IMAGE_NAME:$VERSION .

      # 4. Harbor 푸시 (포트 포함 명령어)
      - name: Push to Harbor
        run: |
          podman login -u ${{ secrets.HARBOR_USER }} -p ${{ secrets.HARBOR_PASSWORD }} $HARBOR_REGISTRY
          podman push $HARBOR_REGISTRY/smarthome/$IMAGE_NAME:$VERSION
          podman tag $HARBOR_REGISTRY/smarthome/$IMAGE_NAME:$VERSION $HARBOR_REGISTRY/smarthome/$IMAGE_NAME:latest
          podman push $HARBOR_REGISTRY/smarthome/$IMAGE_NAME:latest
