name: Update Bootc Client

on:
  workflow_dispatch:

env:
  IMAGE_NAME: my_dashboard
  IMAGE_VERSION: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: 이미지 빌드 (Containerfile_Update 사용)
        run: podman build -f Containerfile_Update -t $IMAGE_NAME:$IMAGE_VERSION .

      - name: Harbor 레지스트리 로그인
        run: podman login -u ${{ secrets.HARBOR_USER }} -p ${{ secrets.HARBOR_PASS }} harbor.bootc.com

      - name: 태그 설정 및 푸시
        run: |
          podman tag $IMAGE_NAME:$IMAGE_VERSION harbor.bootc.com/smarthome/$IMAGE_NAME:latest
          podman tag $IMAGE_NAME:$IMAGE_VERSION harbor.bootc.com/smarthome/$IMAGE_NAME:$IMAGE_VERSION
          podman push harbor.bootc.com/smarthome/$IMAGE_NAME:latest
          podman push harbor.bootc.com/smarthome/$IMAGE_NAME:$IMAGE_VERSION
